[package]
name = "simpletask"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.26.0"
num-derive = "0.3.3"
num-traits = "0.2.14"